version: 2.1

commands:
  checkout_with_workspace:
    steps:
      - checkout
      - attach_workspace:
          at: ~/

jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  # JS & SCSS jobs
  lint:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Run SCSS Linter
          command: npm run lint:js
      - run:
          name: Run JS Linter
          command: npm run lint:js
      - run:
          name: Run PHP Linter
          command: |
            composer install
            npm run lint:php

  test-php:
    docker:
      - image: circleci/php:7.2
      - image: circleci/mysql:5.6
    environment:
      - WP_TESTS_DIR: '/tmp/wordpress-tests-lib'
      - WP_CORE_DIR: '/tmp/wordpress/'
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update && sudo apt-get install subversion
            sudo -E docker-php-ext-install mysqli
            sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian sid main\n' >> /etc/apt/sources.list"
            sudo apt-get update && sudo apt-get install mysql-client-5.7
      - run:
          name: Run Tests
          command: |
            composer install
            composer global require "phpunit/phpunit=5.7.*"
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            phpunit

  # Release job
  release:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout_with_workspace
      - run:
          name: Release new version
          command: npm run release

workflows:
  version: 2
  main:
    jobs:
      - lint-php
      - test-php
      - build
      - lint-js-scss:
          requires:
            - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: release
